defaults:
  - partitioning: iid
  - algorithm: splitfedv1
  - dataset: cifar10
  - model: resnet18
  - optimizer: adam
  - device_capacities: simulation
  - _self_
general:
  seed: 10
  num_rounds: 1
client_train_config:
  lte: 1
  batch_size: 16
strategy_config:
  fraction_fit: 1.0
  fraction_evaluate: 1.0
experiment_name: multialgo_comparison
loss:
  class_weight: [1.0, 50.0]
communication:
  embedding_dim: 64
  bytes_per_float: 4
# bmr:
#   fp_cost: 1.0
#   fn_cost: 100.0
#   tn_cost: 0.0
#   tp_cost: 0.0